[project]
name = "one-template-to-rule-them-all"
version = "0.1.0"
description = "Interactive Research Data Documentation with Quarto - presentation materials for DHTech Symposium at DH2025"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "playwright>=1.53.0",
]
