(function(s,d){typeof exports=="object"&&typeof module<"u"?module.exports=d():typeof define=="function"&&define.amd?define(d):(s=typeof globalThis<"u"?globalThis:s||self).RevealZoom=d()})(this,function(){"use strict";/*!
	 * reveal.js Zoom plugin
	 */const s={id:"zoom",init:function(n){n.getRevealElement().addEventListener("mousedown",function(o){var l=/Linux/.test(window.navigator.platform)?"ctrl":"alt",c=(n.getConfig().zoomKey?n.getConfig().zoomKey:l)+"Key",r=n.getConfig().zoomLevel?n.getConfig().zoomLevel:2;o[c]&&!n.isOverview()&&(o.preventDefault(),d.to({x:o.clientX,y:o.clientY,scale:r,pan:!1}))})},destroy:()=>{d.reset()}};var d=function(){var n=1,o=0,l=0,c=-1,r=-1,u="transform"in document.body.style;function y(e,t){var i=m();if(e.width=e.width||1,e.height=e.height||1,e.x-=(window.innerWidth-e.width*t)/2,e.y-=(window.innerHeight-e.height*t)/2,u)if(t===1)document.body.style.transform="";else{var w=i.x+"px "+i.y+"px",f="translate("+-e.x+"px,"+-e.y+"px) scale("+t+")";document.body.style.transformOrigin=w,document.body.style.transform=f}else t===1?(document.body.style.position="",document.body.style.left="",document.body.style.top="",document.body.style.width="",document.body.style.height="",document.body.style.zoom=""):(document.body.style.position="relative",document.body.style.left=-(i.x+e.x)/t+"px",document.body.style.top=-(i.y+e.y)/t+"px",document.body.style.width=100*t+"%",document.body.style.height=100*t+"%",document.body.style.zoom=t);n=t,document.documentElement.classList&&(n!==1?document.documentElement.classList.add("zoomed"):document.documentElement.classList.remove("zoomed"))}function a(){var e=.12*window.innerWidth,t=.12*window.innerHeight,i=m();l<t?window.scroll(i.x,i.y-14/n*(1-l/t)):l>window.innerHeight-t&&window.scroll(i.x,i.y+(1-(window.innerHeight-l)/t)*(14/n)),o<e?window.scroll(i.x-14/n*(1-o/e),i.y):o>window.innerWidth-e&&window.scroll(i.x+(1-(window.innerWidth-o)/e)*(14/n),i.y)}function m(){return{x:window.scrollX!==void 0?window.scrollX:window.pageXOffset,y:window.scrollY!==void 0?window.scrollY:window.pageYOffset}}return u&&(document.body.style.transition="transform 0.8s ease"),document.addEventListener("keyup",function(e){n!==1&&e.keyCode===27&&d.out()}),document.addEventListener("mousemove",function(e){n!==1&&(o=e.clientX,l=e.clientY)}),{to:function(e){if(n!==1)d.out();else{if(e.x=e.x||0,e.y=e.y||0,e.element){var t=e.element.getBoundingClientRect();e.x=t.left-20,e.y=t.top-20,e.width=t.width+40,e.height=t.height+40}e.width!==void 0&&e.height!==void 0&&(e.scale=Math.max(Math.min(window.innerWidth/e.width,window.innerHeight/e.height),1)),e.scale>1&&(e.x*=e.scale,e.y*=e.scale,y(e,e.scale),e.pan!==!1&&(c=setTimeout(function(){r=setInterval(a,1e3/60)},800)))}},out:function(){clearTimeout(c),clearInterval(r),y({x:0,y:0},1),n=1},magnify:function(e){this.to(e)},reset:function(){this.out()},zoomLevel:function(){return n}}}();/*!
	 * zoom.js 0.3 (modified for use with reveal.js)
	 * http://lab.hakim.se/zoom-js
	 * MIT licensed
	 *
	 * Copyright (C) 2011-2014 Hakim El Hattab, http://hakim.se
	 */return()=>s});
